from .so_adj_ratio import CountStartleFeatures_soAdj, CountStartleFeatures_soAdverbs
from .punctuation import CountStartleFeatures_exclamation, CountStartleFeatures_questionMark, CountStartleFeatures_supriseMark, CountStartleFeatures_ellipsis, CountStartleFeatures_parcelling
from .to import CountStartleFeatures_to
from .when_people import CountFearFeatures_whenPeople
from .parts_of_speech import CountStartleFeatures_Verb, CountStartleFeatures_adjectives, CountFearFeatures_numbers
from .talk import CountFearFeatures_talk_myself, CountFearFeatures_what_talk, CountFearFeatures_colon_talk, CountFearFeatures_talk, CountFearFeatures_doctor_talk,  CountFearFeatures_toldMe
from .comparative import CountFearFeatures_adjComparative, CountFearFeatures_adjSuperb, CountFearFeatures_caps
from .calc_tokens import calc_tokens_feature